#!/bin/sh

#   WARNING   this file is automatically generated by RT-Druid

#   If you want modify this file, you should move it to a safe folder,
#   like the project's root, and update the path inside the project 
#   properties "C/C++ Make Project" -> "Build command"
#   i.e.   ${workspace_loc:lcd1602_boom}/make_launcher.bat


ERIKA_FILES=/opt/case/evidence/eclipse/plugins/com.eu.evidence.ee_2.4.0.N20140917_2014/ee_files
export ERIKA_FILES

make $@
